// <auto-generated />
namespace B4B.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WizardViewModelUpdated2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WizardViewModelUpdated2));
        
        string IMigrationMetadata.Id
        {
            get { return "201608210151223_WizardViewModel Updated(2)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
