// <auto-generated />
namespace B4B.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emergencyphonetwilio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emergencyphonetwilio));
        
        string IMigrationMetadata.Id
        {
            get { return "201608221504419_emergency phone twilio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
